# Generated by Django 3.1.2 on 2020-11-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
