# Generated by Django 3.0.3 on 2020-10-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0002_auto_20201013_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
