# Generated by Django 3.1.2 on 2020-10-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0003_auto_20201016_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
