# Generated by Django 3.0.3 on 2020-10-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0004_auto_20201018_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
