# Generated by Django 3.0.3 on 2020-10-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0006_auto_20201019_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
