# Generated by Django 3.1.2 on 2020-10-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0008_auto_20201029_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
