# Generated by Django 3.1.2 on 2020-11-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0009_userbase_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_mod',
            field=models.BooleanField(default=False),
        ),
    ]
