# Generated by Django 2.2.2 on 2020-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('is_running', models.BooleanField(default=False)),
                ('has_container', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('container_id', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
