# Generated by Django 3.1.2 on 2020-10-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_erp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='erp',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
