# Generated by Django 3.1.2 on 2020-11-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_erp_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
