# Generated by Django 3.1.2 on 2020-11-03 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_remove_credit_erp'),
        ('erp', '0002_erp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='erp',
            name='credit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='commerce.credit'),
            preserve_default=False,
        ),
    ]
