# Generated by Django 3.0.3 on 2020-11-04 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20201104_0722'),
        ('erp', '0002_erp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erp',
            name='credit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='erp', to='commerce.Credit'),
        ),
    ]
