# Generated by Django 3.1.2 on 2020-10-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20201015_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='0.0.0.0', max_length=255)),
                ('current_port', models.PositiveIntegerField(default='9000')),
                ('available_ports', models.TextField(default='[]')),
            ],
        ),
        migrations.AddField(
            model_name='erp',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=9000, null=True),
        ),
    ]
