# Generated by Django 3.1.2 on 2020-11-01 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('time_in_days', models.PositiveIntegerField(default=30)),
                ('number_of_erp', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=1000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_days', models.PositiveIntegerField()),
                ('used_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('bill_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('pure_total_amount', models.FloatField()),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_note', models.TextField()),
                ('payment_verification', models.TextField()),
                ('time_in_days', models.PositiveIntegerField()),
                ('number_of_erp', models.PositiveIntegerField()),
                ('is_bundle', models.BooleanField(default=False)),
                ('is_refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('erp_number', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=1000)),
            ],
            options={
                'unique_together': {('erp_number',)},
            },
        ),
    ]
