# Generated by Django 3.1.2 on 2020-11-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20201109_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='grace_period_in_days',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='setting',
            name='lowest_purchase_time_limit_in_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
