# Generated by Django 3.1.2 on 2020-11-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20201118_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='grace_period_in_hours',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AlterField(
            model_name='setting',
            name='lowest_purchase_time_limit_in_hours',
            field=models.PositiveIntegerField(default=720),
        ),
    ]
