# Generated by Django 3.1.2 on 2020-11-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20201102_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='number_of_erp',
            new_name='number_of_erps',
        ),
    ]
