# Generated by Django 3.1.2 on 2020-11-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20201102_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_converted_to_credits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
