# Generated by Django 3.1.2 on 2020-11-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20201102_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='erp',
        ),
    ]
